### ISSUE TITLE
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by ttasovac** [hackmdio/codimd-container#24]
Uploading an 1.1MB image file to imgur results in `Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)`.

This is probably related to the server's maximum upload size. Is there a way to increase it?

Many thanks in advance.

**Comment by ccoenen** [comment]
Different sources say different things, but the only canonical places I found for filesizes were these:

https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139 (states maximum of 10MB)
https://help.imgur.com/hc/en-us/articles/115000083326-What-files-can-I-upload-What-is-the-size-limit- (basically: should work for larger files up to 20MB)

I have no idea which is right.

**Comment by MelBourbon** [comment]
Nginx webserver also has a default `client_max_body_size` of `1MB` which if not changed leads to this error message. And file will need to go through your server first to get to imgur.

**Comment by SISheogorath** [comment]
Since I think this is in itself out of the scope outside of this repository, let's close this one.

Closing this issues, doesn't mean you are not allowed to continue the discussion and sharing tips :)

I'm sure we welcome useful documentation for setting up CodiMD with nginx or similar in [our docs section](https://github.com/hackmdio/codimd/tree/master/docs/guides). Maybe have a look at: https://nginxconfig.io/ :)
