### ISSUE TITLE
invalid host "hackmdio/hackmd" in Nginx reverseproxy 

### ISSUE THREAD

**Issue by jianlianggao** [hackmdio/codimd-container#3]
Dear dev team,

I have run the dockerized hackmd on my local server. Now I would like to add hackmd service to my server webservice. When I config Nginx config and added hackmdio/hackmd:3000 to my upstream server. The Nginx complained that it was an invalid host. 

Any suggestion? Please. Many thanks.

Best regards,
Jianliang

**Comment by mouson** [comment]
What Setting Value is your  docker-compose.yml ?
CMD_DOMAIN ?
CMD_URL_ADDPORT ?

**Comment by jianlianggao** [comment]
Hi Mouson,

I just added a port to the session of services
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8000:8080
            - 8081:3000
        restart: always

**Comment by SISheogorath** [comment]
Can you provide your configs (with codeblocks) and the docker-compose file? (Of course remove all secrets before sharing)

Because right now it doesn't make a lot of sense. `hackmdio/hackmd:3000` is not a valid hostname, so far, nginx is correct. But I'm not sure how you want to connect your reverse proxy. Does it run in docker? Does it run on the host? Does it run on another machine?

**Comment by jianlianggao** [comment]
Hi,
Thank you very much for your help. I have just sorted out this issue. It was my fault as I used hackmd docker as my upstream server in the Nginx docker container. Because my hackmd is running on my computer, the upstream server should point to my computer where the hackmd is hosted. Again, thank you very much for this discussion.

Best regards,
Jianliang
